import test from 'node:test';
import assert from 'node:assert/strict';
import { renderKittyConf } from '../integrations/kitty/render.js';
import { liveCommands } from '../integrations/kitty/live.js';

const resolved = { params: {
  'terminal.background.opacity.active': 0.95,
  'terminal.background.opacity.inactive': 0.65,
} };

test('persistent conf carries the active opacity', () => {
  const conf = renderKittyConf(resolved);
  assert.match(conf, /^# generated by prism/);
  assert.match(conf, /^background_opacity 0\.95$/m);
});

test('live: all windows inactive, then focused os window active by window id', () => {
  const osWindows = [
    { id: 1, is_focused: false, tabs: [{ windows: [{ id: 11 }] }] },
    { id: 2, is_focused: true, tabs: [{ windows: [{ id: 21 }, { id: 22 }] }] },
  ];
  assert.deepEqual(liveCommands(resolved, osWindows), [
    ['set-background-opacity', '--all', '0.65'],
    ['set-background-opacity', '--match', 'id:21', '0.95'],
  ]);
});

test('live: no focused os window -> everything inactive, no active command', () => {
  const osWindows = [{ id: 1, is_focused: false, tabs: [{ windows: [{ id: 11 }] }] }];
  assert.deepEqual(liveCommands(resolved, osWindows),
    [['set-background-opacity', '--all', '0.65']]);
});
