import test from 'node:test';
import assert from 'node:assert/strict';
import { renderKittyConf } from '../integrations/kitty/render.js';
import { applyToKittySockets, kittySockets, liveCommands } from '../integrations/kitty/live.js';

const resolved = { params: {
  'terminal.background.opacity.active': 0.95,
  'terminal.background.opacity.inactive': 0.65,
} };

test('persistent conf carries the active opacity', () => {
  const conf = renderKittyConf(resolved);
  assert.match(conf, /^# generated by prism/);
  assert.match(conf, /^background_opacity 0\.95$/m);
});

test('live: all windows inactive, then focused os window active by window id', () => {
  const osWindows = [
    { id: 1, is_focused: false, tabs: [{ windows: [{ id: 11 }] }] },
    { id: 2, is_focused: true, tabs: [{ windows: [{ id: 21 }, { id: 22 }] }] },
  ];
  assert.deepEqual(liveCommands(resolved, osWindows), [
    ['set-background-opacity', '--all', '0.65'],
    ['set-background-opacity', '--match', 'id:21', '0.95'],
  ]);
});

test('live: no focused os window -> everything inactive, no active command', () => {
  const osWindows = [{ id: 1, is_focused: false, tabs: [{ windows: [{ id: 11 }] }] }];
  assert.deepEqual(liveCommands(resolved, osWindows),
    [['set-background-opacity', '--all', '0.65']]);
});

test('socket discovery deduplicates exact pid-suffixed kitty addresses', () => {
  const procNetUnix = `Num RefCount Protocol Flags Type St Inode Path
000: 2 0 10000 1 01 10 @dotfiles-kitty-12
001: 2 0 10000 1 01 11 @dotfiles-kitty-12
002: 2 0 10000 1 01 12 @dotfiles-kitty
003: 2 0 10000 1 01 13 @dotfiles-kitty-12-extra
004: 2 0 10000 1 01 14 prefix@dotfiles-kitty-13
005: 2 0 10000 1 01 15 @dotfiles-kitty-34
`;
  assert.deepEqual(kittySockets(procNetUnix), [
    'unix:@dotfiles-kitty-12',
    'unix:@dotfiles-kitty-34',
  ]);
});

test('socket application fails loudly when discovery finds no exact match', () => {
  assert.deepEqual(kittySockets('Num RefCount Protocol Flags Type St Inode Path\n'), []);
  assert.throws(
    () => applyToKittySockets(resolved, '@not-dotfiles-kitty-1\n', () => {}, () => ''),
    /no kitty remote-control sockets found/,
  );
});

test('socket application requires a fresh proc-net-unix reader', () => {
  assert.throws(
    () => applyToKittySockets(
      resolved,
      '000: 2 0 10000 1 01 10 @dotfiles-kitty-12',
      () => '',
    ),
    /fresh proc-net-unix reader is required/,
  );
});

test('each discovered socket gets its own inactive, ls, optional nested-id active sequence', () => {
  const calls = [];
  const kitten = (socket, args) => {
    calls.push([socket, ...args]);
    if (args[0] !== 'ls') return '';
    return JSON.stringify(socket.endsWith('-12')
      ? [{ id: 1, is_focused: false, tabs: [{ windows: [{ id: 11 }] }] }]
      : [{ id: 2, is_focused: true, tabs: [{ windows: [{ id: 21 }] }] }]);
  };

  applyToKittySockets(resolved, [
    '000: 2 0 10000 1 01 10 @dotfiles-kitty-12',
    '001: 2 0 10000 1 01 11 @dotfiles-kitty-34',
  ].join('\n'), kitten, () => {
    throw new Error('fresh reader should not run after a successful apply');
  });

  assert.deepEqual(calls, [
    ['unix:@dotfiles-kitty-12', 'set-background-opacity', '--all', '0.65'],
    ['unix:@dotfiles-kitty-12', 'ls'],
    ['unix:@dotfiles-kitty-34', 'set-background-opacity', '--all', '0.65'],
    ['unix:@dotfiles-kitty-34', 'ls'],
    ['unix:@dotfiles-kitty-34', 'set-background-opacity', '--match', 'id:21', '0.95'],
  ]);
});

test('a vanished socket does not block a later socket from applying', () => {
  const calls = [];
  const kitten = (socket, args) => {
    calls.push([socket, ...args]);
    if (socket.endsWith('-12')) throw new Error('listener vanished');
    return args[0] === 'ls' ? '[]' : '';
  };

  applyToKittySockets(resolved, [
    '000: 2 0 10000 1 01 10 @dotfiles-kitty-12',
    '001: 2 0 10000 1 01 11 @dotfiles-kitty-34',
  ].join('\n'), kitten, () =>
    '001: 2 0 10000 1 01 11 @dotfiles-kitty-34');

  assert.deepEqual(calls, [
    ['unix:@dotfiles-kitty-12', 'set-background-opacity', '--all', '0.65'],
    ['unix:@dotfiles-kitty-34', 'set-background-opacity', '--all', '0.65'],
    ['unix:@dotfiles-kitty-34', 'ls'],
  ]);
});

test('a failed socket still present in fresh discovery rethrows the original error', () => {
  const failure = new Error('command failed');
  assert.throws(
    () => applyToKittySockets(
      resolved,
      '000: 2 0 10000 1 01 10 @dotfiles-kitty-12',
      () => { throw failure; },
      () => '000: 2 0 10000 1 01 10 @dotfiles-kitty-12',
    ),
    (error) => error === failure,
  );
});

test('socket application fails loudly when every discovered socket vanishes', () => {
  const calls = [];
  assert.throws(
    () => applyToKittySockets(resolved, [
      '000: 2 0 10000 1 01 10 @dotfiles-kitty-12',
      '001: 2 0 10000 1 01 11 @dotfiles-kitty-34',
    ].join('\n'), (socket) => {
      calls.push(socket);
      throw new Error('listener vanished');
    }, () => 'Num RefCount Protocol Flags Type St Inode Path\n'),
    /every discovered kitty remote-control socket vanished before apply/,
  );
  assert.deepEqual(calls, [
    'unix:@dotfiles-kitty-12',
    'unix:@dotfiles-kitty-34',
  ]);
});
