import test from 'node:test';
import assert from 'node:assert/strict';
import { renderNiriFragment } from '../integrations/niri/render.js';

const resolved = { params: {
  'compositor.gaps': 54,
  'terminal.apps': ['kitty', 'com.mitchellh.ghostty'],
  'terminal.window.opacity.active': 0.93,
  'terminal.window.opacity.inactive': 0.76,
  'glass.enabled': true,
  'glass.paneLip': 5,
  'glass.paneShiftX': 4,
  'glass.paneShiftY': 4,
  'glass.ior': 1.38,
  'glass.thickness': 32,
  'glass.attenuationColor': '#bbc7db',
  'glass.attenuationDistance': 178,
  'glass.chromaticAberration': 0.68,
  'glass.distortion': 0.32,
  'glass.distortionScale': 0.05,
  'glass.anisotropicBlur': 0,
  'glass.jellyFlex': 0.0038,
  'glass.jellyRipple': 0.15,
} };

const with_ = (overrides) => ({ params: { ...resolved.params, ...overrides } });

const MATCHER = 'r#"^(kitty|com\\.mitchellh\\.ghostty)$"#';

const EXPECTED = `// generated by prism — do not edit
layout {
    gaps 54
}
window-rule {
    match app-id=${MATCHER} is-active=true
    opacity 0.93
}
window-rule {
    match app-id=${MATCHER} is-active=false
    opacity 0.76
}
material "terminal-glass" {
    glass {
        ior 1.38
        thickness 32
        attenuation-color "#bbc7db"
        attenuation-distance 178
        chromatic-aberration 0.68
        distortion 0.32 scale=0.05
        anisotropic-blur 0
        jelly-flex 0.0038
        jelly-ripple 0.15
        bevel 9
        offset-x 4
        offset-y 4
    }
}
window-rule {
    match app-id=${MATCHER}
    material "terminal-glass"
    background-effect {
        blur false
        noise 0
        saturation 1
    }
}
`;

test('the accepted material renders as exact native KDL', () => {
  assert.equal(renderNiriFragment(resolved), EXPECTED);
});

test('the material definition carries every supported native parameter', () => {
  const kdl = renderNiriFragment(resolved);

  assert.match(kdl, /material "terminal-glass" \{\n    glass \{\n/);
  for (const line of [
    'ior 1.38', 'thickness 32', 'attenuation-color "#bbc7db"',
    'attenuation-distance 178', 'chromatic-aberration 0.68',
    'distortion 0.32 scale=0.05', 'anisotropic-blur 0', 'jelly-flex 0.0038',
    'jelly-ripple 0.15', 'bevel 9', 'offset-x 4', 'offset-y 4',
  ]) {
    assert.ok(kdl.includes(`        ${line}\n`), `missing glass line: ${line}`);
  }
});

test('bevel derives from the pane lip and the widest offset', () => {
  const bevel = (over) => renderNiriFragment(with_(over)).match(/bevel (\S+)\n/)[1];

  assert.equal(bevel({ 'glass.paneShiftX': 4, 'glass.paneShiftY': 12 }), '17');
  assert.equal(bevel({ 'glass.paneShiftX': -20, 'glass.paneShiftY': 4 }), '25');
  assert.equal(bevel({ 'glass.paneLip': 0, 'glass.paneShiftX': 0, 'glass.paneShiftY': 0 }), '0');
});

test('the extreme supported geometry stays inside the native bevel maximum', () => {
  const kdl = renderNiriFragment(with_({
    'glass.paneLip': 64, 'glass.paneShiftX': -64, 'glass.paneShiftY': 64,
  }));

  assert.match(kdl, /bevel 128\n/);
  assert.match(kdl, /offset-x -64\n/);
  assert.match(kdl, /offset-y 64\n/);
});

test('terminals match by exact anchored app id, not by substring', () => {
  const kdl = renderNiriFragment(resolved);

  assert.equal(kdl.match(/match app-id=/g)?.length, 3);
  assert.equal(kdl.split(MATCHER).length - 1, 3);
  assert.doesNotMatch(kdl, /app-id="kitty"/);
  assert.doesNotMatch(kdl, /app-id="com\.mitchellh\.ghostty"/);
});

test('opacity rules precede the assignment rule that overrides the legacy pass', () => {
  const kdl = renderNiriFragment(resolved);

  assert.equal(kdl.match(/window-rule \{/g)?.length, 3);
  assert.ok(kdl.indexOf('opacity 0.76') < kdl.indexOf('background-effect {'),
    'the inert background effect must come after the opacity rules');
  assert.match(kdl, /background-effect \{\n        blur false\n        noise 0\n        saturation 1\n    \}/);
  assert.doesNotMatch(kdl, /\bxray\b/);
});

test('disabling glass omits only the material field', () => {
  const kdl = renderNiriFragment(with_({ 'glass.enabled': false }));

  assert.doesNotMatch(kdl, /^\s*material "terminal-glass"$/m);
  assert.match(kdl, /material "terminal-glass" \{/);
  assert.equal(kdl.match(/window-rule \{/g)?.length, 3);
  assert.match(kdl, /background-effect \{\n        blur false\n/);
  assert.match(kdl, /opacity 0\.93\n/);
  assert.equal(renderNiriFragment(with_({ 'glass.enabled': false })),
    EXPECTED.replace('    material "terminal-glass"\n', ''));
});

test('an empty terminal list emits no window rules and no empty regex', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.apps': [] }));

  assert.doesNotMatch(kdl, /window-rule/);
  assert.doesNotMatch(kdl, /app-id/);
  assert.match(kdl, /layout \{\n    gaps 54\n\}/);
  assert.match(kdl, /material "terminal-glass" \{/);
});

test('regex metacharacters in an app id are escaped, not interpreted', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.apps': ['a.b+c(d)|e', 'f*g'] }));

  assert.ok(kdl.includes('r#"^(a\\.b\\+c\\(d\\)\\|e|f\\*g)$"#'), kdl);
});

test('a literal containing a raw-string terminator selects a longer delimiter', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.apps': ['we"#ird'] }));

  assert.ok(kdl.includes('r##"^(we"#ird)$"##'), kdl);

  const deeper = renderNiriFragment(with_({ 'terminal.apps': ['we"##ird'] }));
  assert.ok(deeper.includes('r###"^(we"##ird)$"###'), deeper);
});

test('whole-number opacity remains a KDL float', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.window.opacity.active': 1 }));

  assert.match(kdl, /is-active=true\n    opacity 1\.0\n/);
});

test('fragment is stable', () => {
  assert.equal(renderNiriFragment(resolved), renderNiriFragment(resolved));
});
