import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { parse } from 'yaml';
import { renderNiriFragment, DRY, sourceColors } from '../integrations/niri/render.js';
import { noctaliaColorsPath, readNoctaliaPalette } from '../integrations/niri/palette.js';
import { loadDefs } from '../src/defs.js';
import { defsDir, stateDir } from '../src/paths.js';
import { resolveParams } from '../src/resolve.js';

const resolved = { params: {
  'compositor.gaps': 54,
  'terminal.apps': ['kitty', 'com.mitchellh.ghostty'],
  'glass.enabled': true,
  'glass.paneLip': 5,
  'glass.paneShiftX': 4,
  'glass.paneShiftY': 4,
  'glass.ior': 1.38,
  'glass.lightIor': 9,
  'glass.thickness': 32,
  'glass.tintSource': 'manual',
  'glass.tintAccentMix': 0.1,
  'glass.attenuationColor': '#bbc7db',
  'glass.attenuationDistance': 178,
  'glass.chromaticAberration': 0.68,
  'glass.distortion': 0.32,
  'glass.distortionScale': 0.05,
  'glass.anisotropicBlur': 0,
  'glass.roughness': 0.08,
  'glass.backdropBlur': true,
  'glass.jellyFlex': 0.0038,
  'glass.jellyRipple': 0.15,
  'glass.focusSplit': true,
  'glass.inactive.roughness': 0.5,
  'glass.inactive.ior': 1.52,
  'glass.inactive.thickness': 44,
  'glass.inactive.attenuationColor': '#2a2f3a',
  'glass.inactive.distortionScale': 0.4,
  'glass.inactive.backdropBlur': false,
  'glass.inactive.attenuationDistance': 70,
  'glass.inactive.chromaticAberration': 0.08,
  'glass.inactive.distortion': 0.1,
  'glass.inactive.anisotropicBlur': 0.02,
  'glass.noise': 0,
  'glass.noiseType': 'fine',
  'glass.saturation': 1,
  'glass.inactive.noise': 0.02,
  'glass.inactive.saturation': 0.85,
  'glass.iridescence': 0,
  'glass.aurora': 0,
  'glass.auroraDriftHz': 4,
  'glass.auroraColorA': "#3dffb0",
  'glass.auroraColorB': "#7a5cff",
  'glass.inactive.iridescence': 0,
  'glass.inactive.aurora': 0,
  'glass.inactive.auroraDriftHz': 4,
  'glass.inactive.auroraColorA': "#3dffb0",
  'glass.inactive.auroraColorB': "#7a5cff",
  'glass.bypass.iridescence': false, 'glass.bypass.aurora': false,
  'glass.bypass.backdrop': false,
  'glass.bypass.distortion': false,
  'glass.bypass.refraction': false,
  'glass.bypass.fringing': false,
  'glass.bypass.directionalBlur': false,
  'glass.bypass.tint': false,
  'glass.bypass.saturation': false,
  'glass.bypass.noise': false,
  'glass.ring.focus': true,
  'glass.ring.colorSource': 'manual',
  'glass.ring.color': '#f2c14e',
  'glass.ring.beamSpeed': 450,
  'glass.ring.beamNoise': 0.4,
  'glass.ring.beamNoiseHz': 2.5,
  'glass.ring.decay': 1800,
  'glass.ring.gap': 10,
  'glass.ring.width': 4,
  'glass.ring.glow': 1.2,
  'glass.ring.rest': 0.5,
  'glass.ring.accent': 0.25,
  'glass.ring.edgeTint': false,
} };

const with_ = (overrides) => ({ params: { ...resolved.params, ...overrides } });

const MATCHER = 'r#"^(kitty|com\\.mitchellh\\.ghostty)$"#';

const EXPECTED = `// generated by prism — do not edit
layout {
    gaps 54
    focus-ring { off; }
}
material "terminal-glass" {
    glass {
        ior 1.38
        light-ior 9
        thickness 32
        attenuation-color "#bbc7db"
        attenuation-distance 178
        chromatic-aberration 0.68
        distortion 0.32 scale=0.05
        anisotropic-blur 0
        roughness 0.08
        iridescence 0
        aurora 0 {
            drift-hz 4
            color "#3dffb0"
            color "#7a5cff"
        }
        noise 0 type="fine"
        saturation 1
        backdrop-blur true
        jelly-flex 0.0038
        jelly-ripple 0.15
        bevel 9
        offset-x 4
        offset-y 4
    }
    response "default" {
        accent "none"
        focus "ring-light"
        attention "none"
        ring-color "#f2c14e"
        ring-beam-speed 450
        ring-beam-noise 0.4
        ring-beam-noise-hz 2.5
        ring-beam-decay 1800
        ring-gap 10
        ring-width 4
        ring-glow 1.2
        ring-rest 0.5
        ring-accent 0.25
    }
}
material "terminal-glass-inactive" {
    glass {
        ior 1.52
        light-ior 9
        thickness 44
        attenuation-color "#2a2f3a"
        attenuation-distance 70
        chromatic-aberration 0.08
        distortion 0.1 scale=0.4
        anisotropic-blur 0.02
        roughness 0.5
        iridescence 0
        aurora 0 {
            drift-hz 4
            color "#3dffb0"
            color "#7a5cff"
        }
        noise 0.02 type="fine"
        saturation 0.85
        backdrop-blur false
        jelly-flex 0.0038
        jelly-ripple 0.15
        bevel 9
        offset-x 4
        offset-y 4
    }
    response "default" {
        accent "none"
        focus "ring-light"
        attention "none"
        ring-color "#f2c14e"
        ring-beam-speed 450
        ring-beam-noise 0.4
        ring-beam-noise-hz 2.5
        ring-beam-decay 1800
        ring-gap 10
        ring-width 4
        ring-glow 1.2
        ring-rest 0.5
        ring-accent 0.25
    }
}
window-rule {
    match app-id=${MATCHER} is-active=true
    material "terminal-glass"
    background-effect {
        blur false
        noise 0
        saturation 1
    }
}
window-rule {
    match app-id=${MATCHER} is-active=false
    material "terminal-glass-inactive"
    background-effect {
        blur false
        noise 0
        saturation 1
    }
}
`;

// Without the focus split there is one material and one assignment rule.
const UNSPLIT = `// generated by prism — do not edit
layout {
    gaps 54
    focus-ring { off; }
}
material "terminal-glass" {
    glass {
        ior 1.38
        light-ior 9
        thickness 32
        attenuation-color "#bbc7db"
        attenuation-distance 178
        chromatic-aberration 0.68
        distortion 0.32 scale=0.05
        anisotropic-blur 0
        roughness 0.08
        iridescence 0
        aurora 0 {
            drift-hz 4
            color "#3dffb0"
            color "#7a5cff"
        }
        noise 0 type="fine"
        saturation 1
        backdrop-blur true
        jelly-flex 0.0038
        jelly-ripple 0.15
        bevel 9
        offset-x 4
        offset-y 4
    }
    response "default" {
        accent "none"
        focus "ring-light"
        attention "none"
        ring-color "#f2c14e"
        ring-beam-speed 450
        ring-beam-noise 0.4
        ring-beam-noise-hz 2.5
        ring-beam-decay 1800
        ring-gap 10
        ring-width 4
        ring-glow 1.2
        ring-rest 0.5
        ring-accent 0.25
    }
}
window-rule {
    match app-id=${MATCHER}
    material "terminal-glass"
    background-effect {
        blur false
        noise 0
        saturation 1
    }
}
`;

// Glass off: no material definition, no assignment, no focus-ring override.
// Everything left is upstream niri vocabulary, so a stock niri parses it.
const GLASS_OFF = `// generated by prism — do not edit
layout {
    gaps 54
}
window-rule {
    match app-id=${MATCHER}
    background-effect {
        blur false
        noise 0
        saturation 1
    }
}
`;

test('the focus split inherits only the slab geometry, the pane motion, and the grain type', () => {
  const kdl = renderNiriFragment(resolved);
  const inactive = kdl.match(/material "terminal-glass-inactive" \{[^]*?\n\}\n/)[0];

  for (const line of [
    'jelly-flex 0.0038', 'jelly-ripple 0.15', 'bevel 9', 'offset-x 4', 'offset-y 4',
    'light-ior 9',
  ]) assert.ok(inactive.includes(`        ${line}\n`), `inherited line missing: ${line}`);
  for (const line of [
    'attenuation-distance 70', 'chromatic-aberration 0.08', 'distortion 0.1 scale=0.4',
    'anisotropic-blur 0.02', 'roughness 0.5', 'noise 0.02 type="fine"', 'saturation 0.85',
    'ior 1.52', 'thickness 44', 'attenuation-color "#2a2f3a"', 'backdrop-blur false',
  ]) assert.ok(inactive.includes(`        ${line}\n`), `override missing: ${line}`);
});

test('the unfocused slab keeps the focused frame so focus never resizes the glass', () => {
  const kdl = renderNiriFragment(with_({
    'glass.paneLip': 9, 'glass.paneShiftX': -7, 'glass.paneShiftY': 3,
  }));
  const [active, inactive] = kdl.match(/material "terminal-glass(?:-inactive)?" \{[^]*?\n\}\n/g);
  const frame = (block) => block.match(/bevel \S+\n|offset-[xy] \S+\n/g);

  assert.deepEqual(frame(inactive), frame(active));
  assert.deepEqual(frame(active), ['bevel 16\n', 'offset-x -7\n', 'offset-y 3\n']);
});

test('the focus split assigns materials by is-active', () => {
  const kdl = renderNiriFragment(resolved);

  assert.equal(kdl.match(/window-rule \{/g)?.length, 2);
  assert.equal(kdl.match(/match app-id=/g)?.length, 2);
  assert.match(kdl, /is-active=true\n    material "terminal-glass"\n/);
  assert.match(kdl, /is-active=false\n    material "terminal-glass-inactive"\n/);
  assert.equal(kdl.match(/background-effect \{/g)?.length, 2);
  assert.doesNotMatch(kdl, /\bopacity\b/);
});

test('turning the focus split off renders one material and one assignment', () => {
  const kdl = renderNiriFragment(with_({ 'glass.focusSplit': false }));

  assert.equal(kdl, UNSPLIT);
  assert.doesNotMatch(kdl, /terminal-glass-inactive/);
  assert.equal(kdl.match(/window-rule \{/g)?.length, 1);
});

test('the accepted material renders as exact native KDL', () => {
  assert.equal(renderNiriFragment(resolved), EXPECTED);
});

test('the material definition carries every supported native parameter', () => {
  const kdl = renderNiriFragment(resolved);

  assert.match(kdl, /material "terminal-glass" \{\n    glass \{\n/);
  for (const line of [
    'ior 1.38', 'light-ior 9', 'thickness 32', 'attenuation-color "#bbc7db"',
    'attenuation-distance 178', 'chromatic-aberration 0.68',
    'distortion 0.32 scale=0.05', 'anisotropic-blur 0', 'roughness 0.08', 'noise 0 type="fine"', 'saturation 1',
    'backdrop-blur true',
    'jelly-flex 0.0038',
    'jelly-ripple 0.15', 'bevel 9', 'offset-x 4', 'offset-y 4',
  ]) {
    assert.ok(kdl.includes(`        ${line}\n`), `missing glass line: ${line}`);
  }
});

test('bevel derives from the pane lip and the widest offset', () => {
  const bevel = (over) => renderNiriFragment(with_(over)).match(/bevel (\S+)\n/)[1];

  assert.equal(bevel({ 'glass.paneShiftX': 4, 'glass.paneShiftY': 12 }), '17');
  assert.equal(bevel({ 'glass.paneShiftX': -20, 'glass.paneShiftY': 4 }), '25');
  assert.equal(bevel({ 'glass.paneLip': 0, 'glass.paneShiftX': 0, 'glass.paneShiftY': 0 }), '0');
});

test('the extreme supported geometry stays inside the native bevel maximum', () => {
  const kdl = renderNiriFragment(with_({
    'glass.paneLip': 64, 'glass.paneShiftX': -64, 'glass.paneShiftY': 64,
  }));

  assert.match(kdl, /bevel 128\n/);
  assert.match(kdl, /offset-x -64\n/);
  assert.match(kdl, /offset-y 64\n/);
});

// The geometry rules the native parser still has, after the ring beam moved
// the band under the face (niri-material docs/materials/material-config.md):
// bevel is 0..128 and no offset may be wider than its own bevel. The retired
// rule was ring-inset + ring-width <= bevel; the band now sits ring-gap px
// inside the face edge and the bevel shrinks to make room, so no minimum
// bevel exists and prism must not reinstate one as a clamp or a floor.
const NATIVE_BEVEL = [0, 128];

const geometryOf = (kdl) => ({
  bevels: [...kdl.matchAll(/bevel (\S+)\n/g)].map((match) => Number(match[1])),
  offsets: [...kdl.matchAll(/offset-[xy] (\S+)\n/g)].map((match) => Number(match[1])),
});

const assertNativeGeometry = (kdl, label) => {
  const { bevels, offsets } = geometryOf(kdl);
  for (const bevel of bevels) {
    assert.ok(bevel >= NATIVE_BEVEL[0] && bevel <= NATIVE_BEVEL[1], `${label}: bevel ${bevel}`);
  }
  for (const offset of offsets) {
    assert.ok(Math.abs(offset) <= bevels[0],
      `${label}: offset ${offset} exceeds bevel ${bevels[0]}`);
  }
  return bevels;
};

test('the neutral geometry meets every geometry rule the native parser keeps', () => {
  const params = Object.fromEntries([...loadDefs(defsDir())].map(([key, def]) =>
    [key, Object.hasOwn(def, 'neutral') ? def.neutral : def.default]));
  const kdl = renderNiriFragment({ params: { ...params, 'glass.focusSplit': true } });

  assert.deepEqual(assertNativeGeometry(kdl, 'neutral'), [8, 8]);
});

// Every case is reachable from the panel's own ranges, and each one was
// validated by the installed niri-material build before it was pinned here.
// The last is the case the retired rule would have rejected: a ring gap wider
// than the bevel is now ordinary, because the band is under the face.
const GEOMETRY = [
  { label: 'zero lip and zero offsets leave a flat slab',
    over: { 'glass.paneLip': 0, 'glass.paneShiftX': 0, 'glass.paneShiftY': 0 }, bevel: 0 },
  { label: 'zero lip with the widest supported offsets',
    over: { 'glass.paneLip': 0, 'glass.paneShiftX': -64, 'glass.paneShiftY': 64 }, bevel: 64 },
  { label: 'the shipped ring placement under a small bevel',
    over: { 'glass.paneLip': 1, 'glass.paneShiftX': 1, 'glass.paneShiftY': 0 }, bevel: 2 },
  { label: 'an explicit face placement: ring gap 20 under bevel 12',
    over: { 'glass.paneLip': 6, 'glass.paneShiftX': 6, 'glass.paneShiftY': -6, 'glass.ring.gap': 20 },
    bevel: 12 },
];

test('every small-pane geometry the panel can reach is one niri accepts', () => {
  for (const { label, over, bevel } of GEOMETRY) {
    const kdl = renderNiriFragment(with_(over));

    assert.deepEqual(assertNativeGeometry(kdl, label), [bevel, bevel], label);
    const gap = Object.hasOwn(over, 'glass.ring.gap')
      ? over['glass.ring.gap'] : resolved.params['glass.ring.gap'];
    assert.equal(count(kdl, `ring-gap ${gap}\n`), 2, label);
  }
});

test('a bevel of zero keeps the ring: only the chamfer spill needs a chamfer', () => {
  const kdl = renderNiriFragment(with_(GEOMETRY[0].over));

  // main.frag: "The ring needs a face to run under, not a chamfer: a flat slab
  // with bevel 0 carries the beam." So a flat slab is not a reason to withhold
  // the focus light, and the response block is written unchanged.
  assert.equal(count(kdl, 'bevel 0\n'), 2);
  assert.equal(count(kdl, 'focus "ring-light"'), 2);
  assert.equal(count(kdl, 'ring-gap 10\n'), 2);
});

test('the ring gap is the small-pane limit, and prism reports it instead of clamping', () => {
  const gap = loadDefs(defsDir()).get('glass.ring.gap');

  // The parser takes any gap in 0..128, but the ring is drawn only where the
  // face half-extent exceeds the gap (main.frag: hasLine), so the widest gap
  // the panel offers needs a face over 256 px on both axes. Prism cannot see
  // the window, so the range stays native and the description carries the
  // limit; narrowing it here would silently rewrite stored profiles.
  assert.deepEqual(gap.range, [0, 128]);
  assert.equal(gap.default, 8);
  assert.match(gap.description, /twice/);
});

test('every ring width the panel can emit is one niri accepts, and no retired key is', () => {
  const width = loadDefs(defsDir()).get('glass.ring.width');

  // niri rejects a zero or negative width ("ring-width must be positive"), so
  // the range's own floor is what keeps that error out of reach: there is no
  // slider position, stored value or reset that can emit a width of zero.
  assert.ok(width.range[0] > 0, `ring width may reach ${width.range[0]}`);
  assert.ok(width.range[1] <= 128, `ring width may reach ${width.range[1]}`);
  assert.equal(width.neutral > 0, true, 'the neutral look emits a width too');

  for (const value of [width.range[0], width.default, width.range[1]]) {
    const kdl = renderNiriFragment(with_({ 'glass.ring.width': value }));
    assert.equal(count(kdl, `ring-width ${value}\n`), 2, `width ${value}`);
  }
  const kdl = renderNiriFragment(resolved);
  for (const retired of ['ring-inset', 'ring-sweep-ms', 'ring-drift-hz']) {
    assert.equal(count(kdl, retired), 0, retired);
  }
});

test('terminals match by exact anchored app id, not by substring', () => {
  const kdl = renderNiriFragment(resolved);

  assert.equal(kdl.match(/match app-id=/g)?.length, 2);
  assert.equal(kdl.split(MATCHER).length - 1, 2);
  assert.doesNotMatch(kdl, /app-id="kitty"/);
  assert.doesNotMatch(kdl, /app-id="com\.mitchellh\.ghostty"/);
});

test('the assignment rule pins the legacy pass off without touching window opacity', () => {
  const kdl = renderNiriFragment(with_({ 'glass.focusSplit': false }));

  assert.equal(kdl.match(/window-rule \{/g)?.length, 1);
  assert.match(kdl, /background-effect \{\n        blur false\n        noise 0\n        saturation 1\n    \}/);
  assert.doesNotMatch(kdl, /\bxray\b/);
  assert.doesNotMatch(kdl, /\bopacity\b/);
});

// A niri without niri-material rejects the whole config over a material node
// it does not know, so glass off must leave none behind: the sink still owns
// gaps, the terminal window rules and the inert background effect.
test('disabling glass omits the material definition, its field and the focus split', () => {
  const kdl = renderNiriFragment(with_({ 'glass.enabled': false }));

  assert.doesNotMatch(kdl, /material/, 'no material node may survive for a stock niri to reject');
  assert.doesNotMatch(kdl, /terminal-glass/);
  assert.equal(kdl.match(/window-rule \{/g)?.length, 1);
  assert.equal(kdl, GLASS_OFF);
});

test('glass turns the gradient focus-ring off; disabling glass leaves it to the host', () => {
  // niri-material lights every focused material window with its own ring of light, so the
  // static gradient ring is switched off in the same layout block niri merges with the host.
  const on = renderNiriFragment(resolved);
  assert.match(on, /^layout \{\n    gaps 54\n    focus-ring \{ off; \}\n\}$/m);

  const off = renderNiriFragment(with_({ 'glass.enabled': false }));
  assert.match(off, /^layout \{\n    gaps 54\n\}$/m);
  assert.doesNotMatch(off, /focus-ring/);
});

test('an empty terminal list emits no window rules and no empty regex', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.apps': [] }));

  assert.doesNotMatch(kdl, /window-rule/);
  assert.doesNotMatch(kdl, /app-id/);
  assert.match(kdl, /layout \{\n    gaps 54\n    focus-ring \{ off; \}\n\}/);
  assert.match(kdl, /material "terminal-glass" \{/);
});

test('regex metacharacters in an app id are escaped, not interpreted', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.apps': ['a.b+c(d)|e', 'f*g'] }));

  assert.ok(kdl.includes('r#"^(a\\.b\\+c\\(d\\)\\|e|f\\*g)$"#'), kdl);
});

const count = (text, needle) => text.split(needle).length - 1;

test('a bypassed device writes its dry value into both materials and nothing else moves', () => {
  const noise = renderNiriFragment(with_({ 'glass.bypass.noise': true }));
  assert.equal(count(noise, 'noise 0 type="fine"'), 2);
  assert.equal(count(noise, 'noise 0.02'), 0);
  assert.equal(count(noise, 'saturation 0.85'), 1, 'the unfocused saturation is untouched');

  const backdrop = renderNiriFragment(with_({ 'glass.bypass.backdrop': true }));
  assert.equal(count(backdrop, 'roughness 0\n'), 2);
  assert.equal(count(backdrop, 'backdrop-blur false'), 2);

  const tint = renderNiriFragment(with_({ 'glass.bypass.tint': true }));
  assert.equal(count(tint, 'attenuation-color "#ffffff"'), 2);
  assert.equal(count(tint, 'attenuation-distance 178'), 1, 'tint distance keeps its focused value');
  assert.equal(count(tint, 'attenuation-distance 70'), 1, 'tint distance keeps its unfocused value');

  const distortion = renderNiriFragment(with_({ 'glass.bypass.distortion': true }));
  assert.equal(count(distortion, 'distortion 0 scale=0.05'), 1);
  assert.equal(count(distortion, 'distortion 0 scale=0.4'), 1);

  // Both window rules carry an inert `saturation 1` of their own, so the two
  // materials make four in total; the unfocused 0.85 is what must be gone.
  const saturation = renderNiriFragment(with_({ 'glass.bypass.saturation': true }));
  assert.equal(count(saturation, 'saturation 1\n'), 4);
  assert.equal(count(saturation, 'saturation 0.85'), 0);

  assert.equal(count(renderNiriFragment(with_({ 'glass.bypass.fringing': true })), 'chromatic-aberration 0\n'), 2);
  assert.equal(count(renderNiriFragment(with_({ 'glass.bypass.directionalBlur': true })), 'anisotropic-blur 0\n'), 2);
});

test('bypassing refraction also silences fringing and directional blur', () => {
  const withDependents = renderNiriFragment(with_({ 'glass.bypass.refraction': true }));
  assert.equal(count(withDependents, 'ior 1\n'), 2);
  assert.equal(count(withDependents, 'chromatic-aberration 0\n'), 2);
  assert.equal(count(withDependents, 'anisotropic-blur 0\n'), 2);
  assert.equal(count(withDependents, 'thickness 32'), 1, 'depth keeps its focused value');
  assert.equal(count(withDependents, 'thickness 44'), 1, 'depth keeps its unfocused value');

  const withoutDependents = renderNiriFragment(with_({
    'glass.bypass.refraction': true,
    'glass.chromaticAberration': 0,
    'glass.inactive.chromaticAberration': 0,
    'glass.anisotropicBlur': 0,
    'glass.inactive.anisotropicBlur': 0,
  }));
  assert.equal(withoutDependents, withDependents);
});

test('every rack device has a dry entry and every dry entry is a rack device', () => {
  const rack = parse(fs.readFileSync(path.join(defsDir(), 'rack', 'devices.yaml'), 'utf8'));
  assert.deepEqual(Object.keys(DRY).sort(), rack.devices.map((device) => device.bypass).sort());
});

test('a literal containing a raw-string terminator selects a longer delimiter', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.apps': ['we"#ird'] }));

  assert.ok(kdl.includes('r##"^(we"#ird)$"##'), kdl);

  const deeper = renderNiriFragment(with_({ 'terminal.apps': ['we"##ird'] }));
  assert.ok(deeper.includes('r###"^(we"##ird)$"###'), deeper);
});

test('noise and saturation are written even when they are neutral', () => {
  const kdl = renderNiriFragment(with_({ 'glass.noise': 0, 'glass.saturation': 1, 'glass.focusSplit': false }));

  // Prism owns both values; it never relies on niri's inheritance from the
  // global blur block, so the neutral pair is written, not omitted.
  assert.match(kdl, /        roughness 0.08\n[^]*        noise 0 type="fine"\n        saturation 1\n        backdrop-blur true\n/);
});

test('every noise type is quoted and shared across glass materials', () => {
  for (const type of ['white', 'fine']) {
    for (const split of [true, false]) {
      const kdl = renderNiriFragment(with_({
        'glass.noiseType': type, 'glass.focusSplit': split,
        'glass.noise': 0.1, 'glass.inactive.noise': 0.02,
      }));
      const materials = kdl.match(/^material [^]*?^\}/gm);
      assert.equal(materials.length, split ? 2 : 1);
      assert.ok(materials[0].includes(`        noise 0.1 type="${type}"\n`));
      if (split) assert.ok(materials[1].includes(`        noise 0.02 type="${type}"\n`));
    }
  }
});

test('fragment is stable', () => {
  assert.equal(renderNiriFragment(resolved), renderNiriFragment(resolved));
});

test('the sink dry values agree with the defs neutrals', () => {
  const defs = loadDefs(defsDir());
  for (const overrides of Object.values(DRY)) {
    for (const [optic, value] of Object.entries(overrides)) {
      for (const key of [`glass.${optic}`, `glass.inactive.${optic}`]) {
        assert.deepEqual(defs.get(key).neutral, value, key);
      }
    }
  }
  const named = new Set(Object.values(DRY).flatMap((o) => Object.keys(o)));
  for (const optic of ['thickness', 'attenuationDistance', 'distortionScale']) {
    assert.equal(named.has(optic), false, optic);
  }
});

test('iridescence and aurora values are independent across focus states', () => {
  const kdl = renderNiriFragment(with_({
    'glass.iridescence': 0.8, 'glass.inactive.iridescence': 0.2,
    'glass.aurora': 0.5, 'glass.inactive.aurora': 0.1,
    'glass.auroraDriftHz': 4, 'glass.inactive.auroraDriftHz': 0,
    'glass.auroraColorA': '#112233', 'glass.auroraColorB': '#445566',
    'glass.inactive.auroraColorA': '#778899', 'glass.inactive.auroraColorB': '#aabbcc',
  }));
  const [active, inactive] = kdl.match(/^material [^]*?^\}/gm);
  assert.match(active, /iridescence 0.8/);
  assert.match(active, /aurora 0.5 \{\n            drift-hz 4\n            color "#112233"\n            color "#445566"/);
  assert.match(inactive, /iridescence 0.2/);
  assert.match(inactive, /aurora 0.1 \{\n            drift-hz 0\n            color "#778899"\n            color "#aabbcc"/);
});

test('optic bypasses silence both states while retaining their settings', () => {
  const params = with_({
    'glass.iridescence': 0.8, 'glass.inactive.iridescence': 0.3,
    'glass.aurora': 0.5, 'glass.inactive.aurora': 0.2,
    'glass.bypass.iridescence': true, 'glass.bypass.aurora': true,
  });
  const before = structuredClone(params);
  const dry = renderNiriFragment(params);
  assert.equal((dry.match(/iridescence 0\n/g) ?? []).length, 2);
  assert.equal((dry.match(/aurora 0 \{/g) ?? []).length, 2);
  assert.deepEqual(params, before);
  const wet = renderNiriFragment({ params: { ...params.params,
    'glass.bypass.iridescence': false, 'glass.bypass.aurora': false } });
  assert.match(wet, /iridescence 0.8/);
  assert.match(wet, /aurora 0.5 \{/);
});

// The ring response is one block, emitted identically into every material the
// split defines: the filament lights only where the window is focused, and a
// signal accent lights any of them.
test('both materials carry the same response block', () => {
  const kdl = renderNiriFragment(resolved);
  const block = '    response "default" {\n        accent "none"\n        focus "ring-light"\n        attention "none"\n'
    + '        ring-color "#f2c14e"\n        ring-beam-speed 450\n'
    + '        ring-beam-noise 0.4\n        ring-beam-noise-hz 2.5\n        ring-beam-decay 1800\n'
    + '        ring-gap 10\n'
    + '        ring-width 4\n        ring-glow 1.2\n        ring-rest 0.5\n        ring-accent 0.25\n    }';

  assert.equal(count(kdl, block), 2, kdl);
  const [active, inactive] = kdl.match(/^material [^]*?^\}/gm);
  assert.ok(active.includes(block));
  assert.ok(inactive.includes(block));
});

test('the resolved shipped defaults reach both material response blocks', () => {
  const kdl = renderNiriFragment({ params: resolveParams(loadDefs(defsDir()), {}) },
    { noctaliaSurface: '#101010', noctaliaAccent: '#202020' });

  assert.equal(count(kdl, 'ring-beam-speed 300'), 2, kdl);
  assert.equal(count(kdl, 'ring-gap 8'), 2, kdl);
  assert.equal(count(kdl, 'ring-width 2.6'), 2, kdl);
  assert.equal(count(kdl, 'ring-glow 1'), 2, kdl);
  assert.equal(count(kdl, 'ring-rest 1'), 2, kdl);
  assert.equal(count(kdl, 'ring-accent 1'), 2, kdl);
  assert.equal(count(kdl, 'attention "rim-orbit"'), 2, kdl);
});

test('the focus light switches off without touching the rest of the response', () => {
  const kdl = renderNiriFragment(with_({ 'glass.ring.focus': false }));

  assert.equal(count(kdl, 'focus "none"'), 2);
  assert.equal(count(kdl, 'ring-color "#f2c14e"'), 2);
  assert.match(kdl, /focus-ring \{ off; \}/, 'the gradient ring stays off for material windows');
});

test('the familiar source leaves the accent channel on and rests on the manual color', () => {
  const kdl = renderNiriFragment(with_({ 'glass.ring.colorSource': 'familiar' }));

  assert.equal(count(kdl, 'accent "ring"'), 2);
  assert.equal(count(kdl, 'ring-color "#f2c14e"'), 2);
});

test('the noctalia source lights the ring in the palette accent the apply read', () => {
  const kdl = renderNiriFragment(with_({ 'glass.ring.colorSource': 'noctalia' }),
    { noctaliaAccent: '#bad065' });

  assert.equal(count(kdl, 'ring-color "#bad065"'), 2);
  assert.equal(count(kdl, 'accent "none"'), 2, 'no second driver may tint the ring');
});

test('the noctalia source rests on the manual color until a palette exists', () => {
  const kdl = renderNiriFragment(with_({ 'glass.ring.colorSource': 'noctalia' }),
    { noctaliaAccent: null });

  assert.equal(count(kdl, 'ring-color "#f2c14e"'), 2);
});

test('the manual source ignores a palette accent', () => {
  const kdl = renderNiriFragment(resolved, { noctaliaAccent: '#bad065' });

  assert.equal(count(kdl, 'ring-color "#f2c14e"'), 2);
  assert.equal(count(kdl, '#bad065'), 0);
});

test('a zero beam speed shows only the resting glow, and the retired sweep key never reaches the config', () => {
  const kdl = renderNiriFragment(with_({ 'glass.ring.beamSpeed': 0 }));

  assert.equal(count(kdl, 'ring-beam-speed 0'), 2);
  assert.equal(count(kdl, 'ring-sweep-ms'), 0);
  assert.equal(count(renderNiriFragment(resolved), 'ring-sweep-ms'), 0);
});

test('the palette reader rests on absence and fails on a broken file', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'prism-palette-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const file = path.join(dir, 'noctalia-palette.json');

  assert.equal(readNoctaliaPalette(file, ['primary']), null, 'a fresh machine has no palette');

  fs.writeFileSync(file, JSON.stringify({ primary: '#BAD065' }));
  assert.deepEqual(readNoctaliaPalette(file, ['primary']), { primary: '#BAD065' }, 'uppercase hex is a color');

  fs.writeFileSync(file, '{ not json');
  assert.throws(() => readNoctaliaPalette(file, ['primary']), /not valid JSON/);

  fs.writeFileSync(file, JSON.stringify({ primary: 'blue' }));
  assert.throws(() => readNoctaliaPalette(file, ['primary']), /primary missing or not a #rrggbb color/);

  fs.writeFileSync(file, JSON.stringify({ mPrimary: '#BAD065' }));
  assert.throws(() => readNoctaliaPalette(file, ['primary']), new RegExp(`${file}: primary missing`),
    'the Noctalia 4 colors.json shape is not a palette');
});

test('the palette defaults to prism state and honours the override', () => {
  const saved = process.env.PRISM_NOCTALIA_COLORS;
  delete process.env.PRISM_NOCTALIA_COLORS;
  try {
    assert.equal(noctaliaColorsPath(), path.join(stateDir(), 'noctalia-palette.json'));
    process.env.PRISM_NOCTALIA_COLORS = '/elsewhere.json';
    assert.equal(noctaliaColorsPath(), '/elsewhere.json');
  } finally {
    if (saved === undefined) delete process.env.PRISM_NOCTALIA_COLORS;
    else process.env.PRISM_NOCTALIA_COLORS = saved;
  }
});

test('palette tint reaches both materials and bypass remains white', () => {
  const input = with_({ 'glass.tintSource': 'noctalia', 'glass.tintAccentMix': 0.1 });
  const before = structuredClone(input);
  const sources = { noctaliaSurface: '#101010', noctaliaAccent: '#202020' };
  const kdl = renderNiriFragment(input, sources);
  assert.equal(count(kdl, 'attenuation-color "#121212"'), 2);
  assert.deepEqual(input, before);
  assert.equal(count(renderNiriFragment(with_({ ...input.params,
    'glass.bypass.tint': true }), {}), 'attenuation-color "#ffffff"'), 2);
  assert.equal(count(renderNiriFragment(with_({ ...input.params,
    'glass.focusSplit': false }), sources), 'attenuation-color "#121212"'), 1);
  for (const [mix, expected] of [[0, '#101010'], [1, '#202020']]) {
    const output = renderNiriFragment(with_({ ...input.params,
      'glass.tintAccentMix': mix }), sources);
    assert.equal(count(output, `attenuation-color "${expected}"`), 2);
  }
  assert.equal(count(renderNiriFragment(with_({ ...input.params,
    'glass.tintAccentMix': 0.25 }), { noctaliaSurface: '#001020',
    noctaliaAccent: '#80c0ff' }), 'attenuation-color "#203c58"'), 2);
  const surfaceOnly = renderNiriFragment(with_({ ...input.params,
    'glass.tintAccentMix': 0 }), { noctaliaSurface: '#ABCDEF' });
  assert.equal(count(surfaceOnly, 'attenuation-color "#abcdef"'), 2);
});

test('palette tint preserves explicit depths and distances and neutral needs no surface', () => {
  const input = with_({ 'glass.tintSource': 'noctalia', 'glass.tintAccentMix': 0.1,
    'glass.thickness': 80, 'glass.inactive.thickness': 40,
    'glass.attenuationDistance': 16, 'glass.inactive.attenuationDistance': 90 });
  const before = structuredClone(input);
  const kdl = renderNiriFragment(input,
    { noctaliaSurface: '#101010', noctaliaAccent: '#202020' });
  for (const value of ['thickness 80', 'thickness 40',
    'attenuation-distance 16', 'attenuation-distance 90']) assert.ok(kdl.includes(value));
  assert.deepEqual(input, before);
  const params = Object.fromEntries([...loadDefs(defsDir())].map(([key, def]) =>
    [key, Object.hasOwn(def, 'neutral') ? def.neutral : def.default]));
  assert.equal(params['glass.tintSource'], 'manual');
  assert.equal(params['glass.tintAccentMix'], 0);
  assert.equal(count(renderNiriFragment({ params }), 'attenuation-color "#ffffff"'), 2);
});

test('Noctalia tint names the missing validated source contract', () => {
  assert.throws(() => renderNiriFragment(with_({ 'glass.tintSource': 'noctalia',
    'glass.tintAccentMix': 0 }), {}), /noctalia tint rendered without a validated surface/);
});

test('palette validation only inspects required fields and names the consumer', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'prism-palette-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const file = path.join(dir, 'palette.json');
  fs.writeFileSync(file, JSON.stringify({ surface: '#ABCDEF', primary: 'unused' }));
  assert.deepEqual(readNoctaliaPalette(file, ['surface']), { surface: '#ABCDEF' });
  assert.throws(() => readNoctaliaPalette(file, ['surface', 'primary']), /primary missing/);
  fs.writeFileSync(file, JSON.stringify({ primary: '#A1B2C3', surface: 'unused' }));
  assert.deepEqual(readNoctaliaPalette(file, ['primary']), { primary: '#A1B2C3' });
  assert.throws(() => readNoctaliaPalette(path.dirname(file), ['surface']), /EISDIR/);
  for (const value of [undefined, null, 123, [], '#123', '#gggggg']) {
    fs.writeFileSync(file, JSON.stringify({ surface: value }));
    assert.throws(() => readNoctaliaPalette(file, ['surface'], 'tint'), /surface missing/);
  }
  fs.writeFileSync(file, '{ broken');
  assert.throws(() => readNoctaliaPalette(file, ['primary'], 'ring'), (error) => {
    assert.match(error.message, /ring's manual Color source/);
    assert.doesNotMatch(error.message, /manual tint/);
    return true;
  });
});

test('sourceColors names exactly the colors a source resolved', () => {
  const palette = { noctaliaSurface: '#101010', noctaliaAccent: '#202020' };
  const params = (overrides) => with_(overrides).params;
  const tint = { value: '#121212', from: 'the Noctalia palette' };
  assert.deepEqual(sourceColors(params({ 'glass.tintSource': 'manual', 'glass.ring.colorSource': 'manual' }), palette), {});
  assert.deepEqual(sourceColors(params({ 'glass.enabled': false, 'glass.tintSource': 'noctalia',
    'glass.ring.colorSource': 'noctalia' }), palette), {});
  assert.deepEqual(sourceColors(params({ 'glass.tintSource': 'noctalia', 'glass.tintAccentMix': 0.1,
    'glass.ring.colorSource': 'manual' }), palette),
  { 'glass.attenuationColor': tint, 'glass.inactive.attenuationColor': tint });
  assert.deepEqual(sourceColors(params({ 'glass.tintSource': 'noctalia', 'glass.bypass.tint': true,
    'glass.ring.colorSource': 'manual' }), {}), {}, 'a bypassed tint needs and reports no palette');
  assert.deepEqual(sourceColors(params({ 'glass.tintSource': 'manual', 'glass.ring.colorSource': 'noctalia' }), palette),
    { 'glass.ring.color': { value: '#202020', from: 'the Noctalia palette' } });
  const stored = params({ 'glass.tintSource': 'manual', 'glass.ring.colorSource': 'noctalia' })['glass.ring.color'];
  assert.deepEqual(sourceColors(params({ 'glass.tintSource': 'manual', 'glass.ring.colorSource': 'noctalia' }),
    { noctaliaAccent: null }),
  { 'glass.ring.color': { value: stored, from: 'the stored Color; no Noctalia palette was found' } });
  assert.deepEqual(sourceColors(params({ 'glass.tintSource': 'manual', 'glass.ring.colorSource': 'familiar' }), {}),
    { 'glass.ring.color': { value: stored, from: "the resting color; each agent session's hue replaces it on its window" } });
});
