import test from 'node:test';
import assert from 'node:assert/strict';
import { renderNiriFragment } from '../integrations/niri/render.js';

const resolved = { params: {
  'compositor.gaps': 54,
  'terminal.apps': ['kitty', 'com.mitchellh.ghostty'],
  'glass.enabled': true,
  'glass.paneLip': 5,
  'glass.paneShiftX': 4,
  'glass.paneShiftY': 4,
  'glass.ior': 1.38,
  'glass.thickness': 32,
  'glass.attenuationColor': '#bbc7db',
  'glass.attenuationDistance': 178,
  'glass.chromaticAberration': 0.68,
  'glass.distortion': 0.32,
  'glass.distortionScale': 0.05,
  'glass.anisotropicBlur': 0,
  'glass.roughness': 0.08,
  'glass.backdropBlur': true,
  'glass.jellyFlex': 0.0038,
  'glass.jellyRipple': 0.15,
  'glass.focusSplit': true,
  'glass.inactive.roughness': 0.5,
  'glass.inactive.attenuationDistance': 70,
  'glass.inactive.chromaticAberration': 0.08,
  'glass.inactive.distortion': 0.1,
  'glass.inactive.anisotropicBlur': 0.02,
  'glass.noise': 0,
  'glass.saturation': 1,
  'glass.inactive.noise': 0.02,
  'glass.inactive.saturation': 0.85,
} };

const with_ = (overrides) => ({ params: { ...resolved.params, ...overrides } });

const MATCHER = 'r#"^(kitty|com\\.mitchellh\\.ghostty)$"#';

const EXPECTED = `// generated by prism — do not edit
layout {
    gaps 54
}
material "terminal-glass" {
    glass {
        ior 1.38
        thickness 32
        attenuation-color "#bbc7db"
        attenuation-distance 178
        chromatic-aberration 0.68
        distortion 0.32 scale=0.05
        anisotropic-blur 0
        roughness 0.08
        noise 0
        saturation 1
        backdrop-blur true
        jelly-flex 0.0038
        jelly-ripple 0.15
        bevel 9
        offset-x 4
        offset-y 4
    }
}
material "terminal-glass-inactive" {
    glass {
        ior 1.38
        thickness 32
        attenuation-color "#bbc7db"
        attenuation-distance 70
        chromatic-aberration 0.08
        distortion 0.1 scale=0.05
        anisotropic-blur 0.02
        roughness 0.5
        noise 0.02
        saturation 0.85
        backdrop-blur true
        jelly-flex 0.0038
        jelly-ripple 0.15
        bevel 9
        offset-x 4
        offset-y 4
    }
}
window-rule {
    match app-id=${MATCHER} is-active=true
    material "terminal-glass"
    background-effect {
        blur false
        noise 0
        saturation 1
    }
}
window-rule {
    match app-id=${MATCHER} is-active=false
    material "terminal-glass-inactive"
    background-effect {
        blur false
        noise 0
        saturation 1
    }
}
`;

// Without the focus split there is one material and one assignment rule.
const UNSPLIT = `// generated by prism — do not edit
layout {
    gaps 54
}
material "terminal-glass" {
    glass {
        ior 1.38
        thickness 32
        attenuation-color "#bbc7db"
        attenuation-distance 178
        chromatic-aberration 0.68
        distortion 0.32 scale=0.05
        anisotropic-blur 0
        roughness 0.08
        noise 0
        saturation 1
        backdrop-blur true
        jelly-flex 0.0038
        jelly-ripple 0.15
        bevel 9
        offset-x 4
        offset-y 4
    }
}
window-rule {
    match app-id=${MATCHER}
    material "terminal-glass"
    background-effect {
        blur false
        noise 0
        saturation 1
    }
}
`;

test('the focus split renders an inactive material that inherits every other glass parameter', () => {
  const kdl = renderNiriFragment(resolved);
  const inactive = kdl.match(/material "terminal-glass-inactive" \{[^]*?\n\}\n/)[0];

  for (const line of [
    'ior 1.38', 'thickness 32', 'attenuation-color "#bbc7db"',
    'backdrop-blur true', 'jelly-flex 0.0038', 'jelly-ripple 0.15', 'bevel 9',
    'offset-x 4', 'offset-y 4',
  ]) assert.ok(inactive.includes(`        ${line}\n`), `inherited line missing: ${line}`);
  for (const line of [
    'attenuation-distance 70', 'chromatic-aberration 0.08', 'distortion 0.1 scale=0.05',
    'anisotropic-blur 0.02', 'roughness 0.5', 'noise 0.02', 'saturation 0.85',
  ]) assert.ok(inactive.includes(`        ${line}\n`), `override missing: ${line}`);
});

test('the focus split assigns materials by is-active', () => {
  const kdl = renderNiriFragment(resolved);

  assert.equal(kdl.match(/window-rule \{/g)?.length, 2);
  assert.equal(kdl.match(/match app-id=/g)?.length, 2);
  assert.match(kdl, /is-active=true\n    material "terminal-glass"\n/);
  assert.match(kdl, /is-active=false\n    material "terminal-glass-inactive"\n/);
  assert.equal(kdl.match(/background-effect \{/g)?.length, 2);
  assert.doesNotMatch(kdl, /\bopacity\b/);
});

test('turning the focus split off renders one material and one assignment', () => {
  const kdl = renderNiriFragment(with_({ 'glass.focusSplit': false }));

  assert.equal(kdl, UNSPLIT);
  assert.doesNotMatch(kdl, /terminal-glass-inactive/);
  assert.equal(kdl.match(/window-rule \{/g)?.length, 1);
});

test('the accepted material renders as exact native KDL', () => {
  assert.equal(renderNiriFragment(resolved), EXPECTED);
});

test('the material definition carries every supported native parameter', () => {
  const kdl = renderNiriFragment(resolved);

  assert.match(kdl, /material "terminal-glass" \{\n    glass \{\n/);
  for (const line of [
    'ior 1.38', 'thickness 32', 'attenuation-color "#bbc7db"',
    'attenuation-distance 178', 'chromatic-aberration 0.68',
    'distortion 0.32 scale=0.05', 'anisotropic-blur 0', 'roughness 0.08', 'noise 0', 'saturation 1',
    'backdrop-blur true',
    'jelly-flex 0.0038',
    'jelly-ripple 0.15', 'bevel 9', 'offset-x 4', 'offset-y 4',
  ]) {
    assert.ok(kdl.includes(`        ${line}\n`), `missing glass line: ${line}`);
  }
});

test('bevel derives from the pane lip and the widest offset', () => {
  const bevel = (over) => renderNiriFragment(with_(over)).match(/bevel (\S+)\n/)[1];

  assert.equal(bevel({ 'glass.paneShiftX': 4, 'glass.paneShiftY': 12 }), '17');
  assert.equal(bevel({ 'glass.paneShiftX': -20, 'glass.paneShiftY': 4 }), '25');
  assert.equal(bevel({ 'glass.paneLip': 0, 'glass.paneShiftX': 0, 'glass.paneShiftY': 0 }), '0');
});

test('the extreme supported geometry stays inside the native bevel maximum', () => {
  const kdl = renderNiriFragment(with_({
    'glass.paneLip': 64, 'glass.paneShiftX': -64, 'glass.paneShiftY': 64,
  }));

  assert.match(kdl, /bevel 128\n/);
  assert.match(kdl, /offset-x -64\n/);
  assert.match(kdl, /offset-y 64\n/);
});

test('terminals match by exact anchored app id, not by substring', () => {
  const kdl = renderNiriFragment(resolved);

  assert.equal(kdl.match(/match app-id=/g)?.length, 2);
  assert.equal(kdl.split(MATCHER).length - 1, 2);
  assert.doesNotMatch(kdl, /app-id="kitty"/);
  assert.doesNotMatch(kdl, /app-id="com\.mitchellh\.ghostty"/);
});

test('the assignment rule pins the legacy pass off without touching window opacity', () => {
  const kdl = renderNiriFragment(with_({ 'glass.focusSplit': false }));

  assert.equal(kdl.match(/window-rule \{/g)?.length, 1);
  assert.match(kdl, /background-effect \{\n        blur false\n        noise 0\n        saturation 1\n    \}/);
  assert.doesNotMatch(kdl, /\bxray\b/);
  assert.doesNotMatch(kdl, /\bopacity\b/);
});

test('disabling glass omits the material field and the focus split', () => {
  const kdl = renderNiriFragment(with_({ 'glass.enabled': false }));

  assert.doesNotMatch(kdl, /^\s*material "terminal-glass"$/m);
  assert.doesNotMatch(kdl, /terminal-glass-inactive/);
  assert.match(kdl, /material "terminal-glass" \{/);
  assert.equal(kdl.match(/window-rule \{/g)?.length, 1);
  assert.match(kdl, /background-effect \{\n        blur false\n/);
  assert.equal(kdl, UNSPLIT.replace('    material "terminal-glass"\n', ''));
});

test('an empty terminal list emits no window rules and no empty regex', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.apps': [] }));

  assert.doesNotMatch(kdl, /window-rule/);
  assert.doesNotMatch(kdl, /app-id/);
  assert.match(kdl, /layout \{\n    gaps 54\n\}/);
  assert.match(kdl, /material "terminal-glass" \{/);
});

test('regex metacharacters in an app id are escaped, not interpreted', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.apps': ['a.b+c(d)|e', 'f*g'] }));

  assert.ok(kdl.includes('r#"^(a\\.b\\+c\\(d\\)\\|e|f\\*g)$"#'), kdl);
});

test('a literal containing a raw-string terminator selects a longer delimiter', () => {
  const kdl = renderNiriFragment(with_({ 'terminal.apps': ['we"#ird'] }));

  assert.ok(kdl.includes('r##"^(we"#ird)$"##'), kdl);

  const deeper = renderNiriFragment(with_({ 'terminal.apps': ['we"##ird'] }));
  assert.ok(deeper.includes('r###"^(we"##ird)$"###'), deeper);
});

test('noise and saturation are written even when they are neutral', () => {
  const kdl = renderNiriFragment(with_({ 'glass.noise': 0, 'glass.saturation': 1, 'glass.focusSplit': false }));

  // Prism owns both values; it never relies on niri's inheritance from the
  // global blur block, so the neutral pair is written, not omitted.
  assert.match(kdl, /        roughness 0.08\n        noise 0\n        saturation 1\n        backdrop-blur true\n/);
});

test('fragment is stable', () => {
  assert.equal(renderNiriFragment(resolved), renderNiriFragment(resolved));
});
