function rule(app, active, params) {
  const state = active ? 'active' : 'inactive';
  const opacity = params[`terminal.window.opacity.${state}`];
  return [
    'window-rule {',
    `    match app-id=${JSON.stringify(app)} is-active=${active}`,
    `    opacity ${Number.isInteger(opacity) ? `${opacity}.0` : opacity}`,
    '    background-effect {',
    ...(params['terminal.blur'] ? ['        blur true'] : []),
    '        xray false',
    `        saturation ${params[`terminal.saturation.${state}`]}`,
    `        noise ${params[`terminal.noise.${state}`]}`,
    '    }',
    '}',
  ].join('\n');
}

export function renderNiriFragment(resolved) {
  const params = resolved.params;
  return [
    '// generated by prism — do not edit',
    `layout {\n    gaps ${params['compositor.gaps']}\n}`,
    ...params['terminal.apps'].flatMap((app) => [
      rule(app, true, params),
      rule(app, false, params),
    ]),
    '',
  ].join('\n');
}
