const MATERIAL = 'terminal-glass';

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function rawKdl(value) {
  let hashes = '#';
  while (value.includes(`"${hashes}`)) hashes += '#';
  return `r${hashes}"${value}"${hashes}`;
}

// terminal.apps holds literal app ids; niri matches them as regexes.
function appMatcher(apps) {
  return apps.length === 0
    ? null
    : rawKdl(`^(${apps.map(escapeRegex).join('|')})$`);
}

function opacityRule(matcher, active, params) {
  const opacity = params[`terminal.window.opacity.${active ? 'active' : 'inactive'}`];
  return [
    'window-rule {',
    `    match app-id=${matcher} is-active=${active}`,
    `    opacity ${Number.isInteger(opacity) ? `${opacity}.0` : opacity}`,
    '}',
  ].join('\n');
}

function definition(params) {
  const bevel = params['glass.paneLip'] + Math.max(
    Math.abs(params['glass.paneShiftX']),
    Math.abs(params['glass.paneShiftY']),
  );
  return [
    `material ${JSON.stringify(MATERIAL)} {`,
    '    glass {',
    `        ior ${params['glass.ior']}`,
    `        thickness ${params['glass.thickness']}`,
    `        attenuation-color ${JSON.stringify(params['glass.attenuationColor'])}`,
    `        attenuation-distance ${params['glass.attenuationDistance']}`,
    `        chromatic-aberration ${params['glass.chromaticAberration']}`,
    `        distortion ${params['glass.distortion']} scale=${params['glass.distortionScale']}`,
    `        anisotropic-blur ${params['glass.anisotropicBlur']}`,
    `        backdrop-blur ${params['glass.backdropBlur']}`,
    `        jelly-flex ${params['glass.jellyFlex']}`,
    `        jelly-ripple ${params['glass.jellyRipple']}`,
    `        bevel ${bevel}`,
    `        offset-x ${params['glass.paneShiftX']}`,
    `        offset-y ${params['glass.paneShiftY']}`,
    '    }',
    '}',
  ].join('\n');
}

// The inert background effect pins the superseded blur/noise pass off for the
// windows this file owns. It needs no xray override: an inert effect never
// reaches niri's automatic xray path.
function assignmentRule(matcher, params) {
  return [
    'window-rule {',
    `    match app-id=${matcher}`,
    ...(params['glass.enabled'] ? [`    material ${JSON.stringify(MATERIAL)}`] : []),
    '    background-effect {',
    '        blur false',
    '        noise 0',
    '        saturation 1',
    '    }',
    '}',
  ].join('\n');
}

export function renderNiriFragment(resolved) {
  const params = resolved.params;
  const matcher = appMatcher(params['terminal.apps']);
  return [
    '// generated by prism — do not edit',
    `layout {\n    gaps ${params['compositor.gaps']}\n}`,
    ...(matcher === null ? [] : [
      opacityRule(matcher, true, params),
      opacityRule(matcher, false, params),
    ]),
    definition(params),
    ...(matcher === null ? [] : [assignmentRule(matcher, params)]),
    '',
  ].join('\n');
}
