const MATERIAL = 'terminal-glass';
const INACTIVE_MATERIAL = 'terminal-glass-inactive';

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function rawKdl(value) {
  let hashes = '#';
  while (value.includes(`"${hashes}`)) hashes += '#';
  return `r${hashes}"${value}"${hashes}`;
}

// terminal.apps holds literal app ids; niri matches them as regexes.
function appMatcher(apps) {
  return apps.length === 0
    ? null
    : rawKdl(`^(${apps.map(escapeRegex).join('|')})$`);
}

function definition(name, params, glass) {
  const bevel = params['glass.paneLip'] + Math.max(
    Math.abs(params['glass.paneShiftX']),
    Math.abs(params['glass.paneShiftY']),
  );
  return [
    `material ${JSON.stringify(name)} {`,
    '    glass {',
    `        ior ${params['glass.ior']}`,
    `        thickness ${params['glass.thickness']}`,
    `        attenuation-color ${JSON.stringify(params['glass.attenuationColor'])}`,
    `        attenuation-distance ${glass.attenuationDistance}`,
    `        chromatic-aberration ${glass.chromaticAberration}`,
    `        distortion ${glass.distortion} scale=${params['glass.distortionScale']}`,
    `        anisotropic-blur ${glass.anisotropicBlur}`,
    `        roughness ${glass.roughness}`,
    `        noise ${glass.noise}`,
    `        saturation ${glass.saturation}`,
    `        backdrop-blur ${params['glass.backdropBlur']}`,
    `        jelly-flex ${params['glass.jellyFlex']}`,
    `        jelly-ripple ${params['glass.jellyRipple']}`,
    `        bevel ${bevel}`,
    `        offset-x ${params['glass.paneShiftX']}`,
    `        offset-y ${params['glass.paneShiftY']}`,
    '    }',
    '}',
  ].join('\n');
}

// The focused glass is the whole glass surface; the unfocused variant
// overrides only the optics that make a pane recede (the Focus matrix).
function activeGlass(params) {
  return {
    attenuationDistance: params['glass.attenuationDistance'],
    chromaticAberration: params['glass.chromaticAberration'],
    distortion: params['glass.distortion'],
    anisotropicBlur: params['glass.anisotropicBlur'],
    roughness: params['glass.roughness'],
    noise: params['glass.noise'],
    saturation: params['glass.saturation'],
  };
}

function inactiveGlass(params) {
  return {
    attenuationDistance: params['glass.inactive.attenuationDistance'],
    chromaticAberration: params['glass.inactive.chromaticAberration'],
    distortion: params['glass.inactive.distortion'],
    anisotropicBlur: params['glass.inactive.anisotropicBlur'],
    roughness: params['glass.inactive.roughness'],
    noise: params['glass.inactive.noise'],
    saturation: params['glass.inactive.saturation'],
  };
}

// The inert background effect pins the superseded blur/noise pass off for the
// windows this file owns. It needs no xray override: an inert effect never
// reaches niri's automatic xray path.
function assignmentRule(matcher, material, active) {
  return [
    'window-rule {',
    `    match app-id=${matcher}${active === undefined ? '' : ` is-active=${active}`}`,
    ...(material === null ? [] : [`    material ${JSON.stringify(material)}`]),
    '    background-effect {',
    '        blur false',
    '        noise 0',
    '        saturation 1',
    '    }',
    '}',
  ].join('\n');
}

export function renderNiriFragment(resolved) {
  const params = resolved.params;
  const matcher = appMatcher(params['terminal.apps']);
  const split = params['glass.enabled'] && params['glass.focusSplit'];
  return [
    '// generated by prism — do not edit',
    `layout {\n    gaps ${params['compositor.gaps']}\n}`,
    definition(MATERIAL, params, activeGlass(params)),
    ...(split ? [definition(INACTIVE_MATERIAL, params, inactiveGlass(params))] : []),
    ...(matcher === null ? []
      : split ? [
        assignmentRule(matcher, MATERIAL, true),
        assignmentRule(matcher, INACTIVE_MATERIAL, false),
      ]
      : [assignmentRule(matcher, params['glass.enabled'] ? MATERIAL : null)]),
    '',
  ].join('\n');
}
