export function renderKittyConf(resolved) {
  return [
    '# generated by prism — do not edit',
    `background_opacity ${resolved.params['terminal.background.opacity.active']}`,
    '',
  ].join('\n');
}
